//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Todo {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Todo.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE MAKE.
        /// </summary>
        internal static string CaptureFlowScrollPage_CaptureFlowScrollPage_CHOOSE_MAKE {
            get {
                return ResourceManager.GetString("CaptureFlowScrollPage_CaptureFlowScrollPage_CHOOSE_MAKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOOKUP.
        /// </summary>
        internal static string CaptureFlowScrollPage_CaptureFlowScrollPage_LOOKUP {
            get {
                return ResourceManager.GetString("CaptureFlowScrollPage_CaptureFlowScrollPage_LOOKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Reg.
        /// </summary>
        internal static string CaptureFlowScrollPage_CaptureFlowScrollPage_Your_number_plate {
            get {
                return ResourceManager.GetString("CaptureFlowScrollPage_CaptureFlowScrollPage_Your_number_plate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make.
        /// </summary>
        internal static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;Current&gt;^[A-Z]{2}[0-9]{2}[A-Z]{3}$)|(?&lt;Prefix&gt;^[A-Z][0-9]{1,3}[A-Z]{3}$)|(?&lt;Suffix&gt;^[A-Z]{3}[0-9]{1,3}[A-Z]$)|(?&lt;DatelessLongNumberPrefix&gt;^[0-9]{1,4}[A-Z]{1,2}$)|(?&lt;DatelessShortNumberPrefix&gt;^[0-9]{1,3}[A-Z]{1,3}$)|(?&lt;DatelessLongNumberSuffix&gt;^[A-Z]{1,2}[0-9]{1,4}$)|(?&lt;DatelessShortNumberSufix&gt;^[A-Z]{1,3}[0-9]{1,3}$).
        /// </summary>
        internal static string VrmEntry_Regex {
            get {
                return ResourceManager.GetString("VrmEntry_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODEL.
        /// </summary>
        internal static string VrmLookupDetailsPage_VrmLookupDetailsPage_MODEL {
            get {
                return ResourceManager.GetString("VrmLookupDetailsPage_VrmLookupDetailsPage_MODEL", resourceCulture);
            }
        }
    }
}
