//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Todo {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Variables {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Variables() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Todo.Variables", typeof(Variables).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string RestVehicleServices_RestVehicleServices_Images {
            get {
                return ResourceManager.GetString("RestVehicleServices_RestVehicleServices_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://foliownwebservices20170204102510.azurewebsites.net.
        /// </summary>
        internal static string VehicleServices_hostUrl {
            get {
                return ResourceManager.GetString("VehicleServices_hostUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://foliownwebservices20170204102510.azurewebsites.net/api.
        /// </summary>
        internal static string VehicleServices_LookupVRM_API {
            get {
                return ResourceManager.GetString("VehicleServices_LookupVRM_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageSearch/Thumb.
        /// </summary>
        internal static string VehicleServices_LookupVRM_ImageSearch_Thumb {
            get {
                return ResourceManager.GetString("VehicleServices_LookupVRM_ImageSearch_Thumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VehicleDetails.
        /// </summary>
        internal static string VehicleServices_LookupVRM_VehicleDetails {
            get {
                return ResourceManager.GetString("VehicleServices_LookupVRM_VehicleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturers.
        /// </summary>
        internal static string VehicleServices_VehicleServices_Manufacturers {
            get {
                return ResourceManager.GetString("VehicleServices_VehicleServices_Manufacturers", resourceCulture);
            }
        }
    }
}
